---
# chapter 1 variables
cache_update_valid_secs: 900
pigpio_archive: files/01_pigpio.zip
pigpio_tmp_dir: /tmp/pigpio
path_to_pigpiod: /usr/local/bin/pigpiod
minimum_pigpiod_version: 68
pigiod_cron_file: 1_pigpiod_ansible

# chapter 2 variables
adafruit_tmp_dir: /tmp/adafruit_rpi
adafruit_git_version: 103b13388585fee0ab65b31c40aaef16d40af0c1
pi_user_kivy_config: /home/pi/.kivy/config.ini
kivy_config_dict_input:
    "%(name)s": "probesysfs,provider=mtdev,param=max_position_x=240,param=max_position_y=320"
boot_config: /boot/config.txt
connected_devices_git_repo_url: "git@github.com:CWRU-Connected-Devices/connected-devices-spring24.git"
connected_devices_git_repo_version: main
repo_directory: "/home/pi/connected-devices"
lampi_app_cron_file: "3_lampiapp_ansible"
lamp_service_cron_file: "2_lampservice_ansible"
